meta_product_name: "Jungbusch 030"
meta_title: "JB030- Where the pink light is!"
meta_description: "Jungbusch 030: Drinks, cocktails and good music in Neukölln, Berlin"
meta_image: "jbmodel3.jpg" # should exist in `app/assets/images/`
