meta_product_name: "Jungbusch 030"
meta_title: "Jungbusch 030 - Neukölln"
meta_description: "Drinks and Cocktails where the pink light is!"
meta_image: "jbmodel3.jpg" # should exist in `app/assets/images/`
